---
  - name: 'freework'
    url: 'https://www.freework.com/'
  - name: 'ifactory'
    url: 'https://www.ifactory.com.br/'
  - name: 'index'
    url: 'https://idx.digital/'
  - name: 'bepid'
    url: 'http://bepid.ifce.edu.br/'
  - name: 'lsbd'
    url: 'http://www.lsbd.ufc.br/lsbd/'
