---
  - name: 'ifactory'
    url: 'http://www.ifactory.com.br/'
  - name: 'index'
    url: 'http://www.indexdigital.com.br/'
  - name: 'bepid'
    url: 'http://bepid.ifce.edu.br/'
  - name: 'lsbd'
    url: 'http://www.lsbd.ufc.br/lsbd/'
