---
  - name: 'programming'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/1/original/coding.png'
  - name: 'self-development'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/5/original/self-improvement.png'
  - name: 'cooking'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/9/original/cooking.png'
  - name: 'literature'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/2/original/literature.png'
  - name: 'martial-arts'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/6/original/martial-arts.png'
  - name: 'video-games'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/3/original/video-games.png'
  - name: 'crypto'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/4/original/bitcoin.png'
  - name: 'beer'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/8/original/beer.png'
