---
  - name: 'rails'
    title: 'Ruby on Rails'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/1/original/rails.png'
  - name: 'angular'
    title: 'AngularJS'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/2/original/angularjs.png'
  - name: 'swift'
    title: 'Swift'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/3/original/swift.png'
  - name: 'cpp'
    title: 'C++'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/4/original/cpp.png'
  - name: 'git'
    title: 'Git'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/5/original/git.png'
  - name: 'scrum'
    title: 'Scrum'
    icon_url: 'https://res.cloudinary.com/rodrigopk/image/upload/v1/6/original/scrum.png'
